//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyEditor.rc
//
#define DialogRegisterButtonCancel      3
#define DialogPropertiesButtonCancel    3
#define DialogAttachmentButtonCancel    3
#define DialogPropertiesButtonPickBackground 4
#define DialogAttachmentButtonVisibility 4
#define DialogPropertiesButtonPickAmbient 5
#define DialogColoredTextButtonPick2    5
#define DialogPropertiesButtonDefaultBackground 6
#define DialogPropertiesButtonPickDiffuse 7
#define DialogPropertiesButtonPickSpecular 8
#define DialogPropertiesButtonDefaultAmbient 9
#define DialogPropertiesButtonDefaultDiffuse 10
#define DialogPropertiesButtonDefaultSpecular 11
#define DialogPropertiesButtonDefaultPower 12
#define DialogPropertiesButtonDefaultQuality 13
#define DialogPropertiesButtonDefaultClippingPlane 14
#define MainMenu                        101
#define BitmapU01                       103
#define BitmapC00                       104
#define BitmapC01                       105
#define BitmapU00                       106
#define BitmapC02                       108
#define BitmapC03                       109
#define BitmapC04                       110
#define BitmapC05                       111
#define BitmapC06                       112
#define BitmapC07                       113
#define BitmapC08                       114
#define BitmapC09                       115
#define BitmapC10                       116
#define BitmapC11                       117
#define BitmapC12                       118
#define BitmapU02                       120
#define BitmapU03                       121
#define BitmapU04                       122
#define BitmapU05                       123
#define BitmapU06                       124
#define BitmapU07                       125
#define BitmapU08                       126
#define BitmapU09                       127
#define BitmapU10                       128
#define BitmapU11                       129
#define BitmapU12                       130
#define MpqMenu                         132
#define ModelMenu                       133
#define _War3ModelEditorIcon            134
#define IconUnknown                     135
#define IconFolder                      136
#define DialogRegister                  137
#define MpqPopupMenu                    138
#define DialogProperties                139
#define TextureMenu                     140
#define TextureMenu2                    141
#define DialogColoredText               141
#define MpqPopupMenu2                   142
#define DialogQuality                   142
#define CameraMenu                      143
#define ManagerMenu2                    144
#define DialogAttachment                144
#define DialogCamera                    145
#define ManagerMenu                     145
#define DialogCollisionShape            146
#define CameraMenu2                     146
#define DialogEventObject               147
#define IconArchive                     147
#define DialogHelper                    148
#define IconImage                       148
#define DialogLight                     149
#define DialogParticleEmitter           150
#define DialogRibbonEmitter             151
#define IconModel                       151
#define DialogParticleEmitter2          152
#define NodeMenu                        152
#define DialogTexture                   153
#define NodeMenu2                       153
#define IconRibbonEmitter               153
#define DialogGeoset                    154
#define IconAttachment                  154
#define DialogGeosetAnimation           155
#define IconBone                        155
#define DialogSequence                  156
#define IconCollisionShape              156
#define DialogGlobalSequence            157
#define IconEventObject                 157
#define DialogMaterial                  158
#define IconHelper                      158
#define DialogTextureAnimation          159
#define IconLight                       159
#define DialogBone                      160
#define IconParticleEmitter2            160
#define DialogNode                      161
#define IconParticleEmitter             161
#define DialogModelProperties           162
#define TrackMenu                       162
#define DialogInterpolator              163
#define TrackMenu2                      163
#define DialogTrack                     164
#define LayerMenu                       164
#define DialogMaterialLayer             165
#define LayerMenu2                      165
#define DialogModelInfo                 166
#define GeosetMenu                      166
#define GeosetMenu2                     167
#define DialogImportGeoset              167
#define DialogLoadingScreen             168
#define VertexMenu                      168
#define DialogTranslate                 169
#define FaceMenu                        169
#define DialogRotate                    170
#define GroupMenu                       170
#define DialogScale                     171
#define ExtentMenu                      171
#define DialogVertices                  172
#define ExtentMenu2                     172
#define DialogFaces                     173
#define FaceMenu2                       173
#define DialogGroups                    174
#define VertexMenu2                     174
#define DialogExtents                   175
#define GroupMenu2                      175
#define DialogVertex                    176
#define DialogFace                      177
#define DialogGroup                     178
#define DialogExtent                    179
#define DialogRegisterButtonOk          1001
#define DialogRegisterButtonMdl         1002
#define DialogRegisterButtonMdx         1003
#define DialogRegisterButtonMpq         1004
#define DialogRegisterButtonW3m         1005
#define DialogPropertiesButtonOk        1005
#define DialogRegisterButtonW3x         1006
#define DialogPropertiesColorBackground 1006
#define DialogRegisterButtonW3n         1007
#define DialogPropertiesButtonUseLighting 1007
#define DialogColoredTextColor2         1007
#define DialogRegisterButtonOpenWith    1008
#define DialogPropertiesColorAmbient    1008
#define DialogPropertiesColorDiffuse    1009
#define DialogRegisterButtonBmp         1009
#define DialogPropertiesColorSpecular   1010
#define DialogRegisterButtonTga         1010
#define DialogPropertiesButtonZoom      1011
#define DialogRegisterButtonPng         1011
#define DialogPropertiesButtonMove      1012
#define DialogRegisterButtonJpg         1012
#define DialogPropertiesButtonAxises    1013
#define DialogRegisterButtonBlp         1013
#define DialogPropertiesButtonDebug     1014
#define DialogRegisterButtonJpeg        1014
#define DialogPropertiesButtonClockwise 1015
#define DialogRegisterButtonPcx         1015
#define DialogPropertiesButtonCounterClockwise 1016
#define DialogPropertiesButtonUseShaders 1017
#define DialogColoredTextColor1         1017
#define DialogPropertiesButtonSolid     1018
#define DialogColoredTextButtonPick1    1018
#define DialogPropertiesButtonWireframe 1019
#define DialogPropertiesButtonPoint     1020
#define DialogColoredTextButtonSolid    1020
#define DialogColoredTextButtonGradient 1021
#define DialogPropertiesButtonCameras   1021
#define DialogColoredTextEditInput      1022
#define DialogPropertiesButtonUseGroundTexture 1022
#define DialogColoredTextEditOutput     1023
#define DialogPropertiesButtonBones     1023
#define DialogColoredTextButtonGenerate 1024
#define DialogPropertiesButtonCollisionShapes 1024
#define DialogColoredTextStaticText     1025
#define DialogPropertiesButtonAttachments 1025
#define DialogQualityButtonOk           1026
#define DialogQualityButtonCancel       1027
#define DialogQualityEdit               1028
#define DialogPropertiesButtonLights    1029
#define DialogPropertiesEditQuality     1030
#define DialogRibbonEmitterButtonOk     1031
#define DialogPropertiesEditPower       1031
#define DialogRibbonEmitterButtonCancel 1032
#define DialogPropertiesEditNear        1032
#define DialogModelPropertiesEditMinX   1032
#define DialogParticleEmitterButtonOk   1033
#define DialogPropertiesEditFar         1033
#define DialogModelPropertiesEditMinY   1033
#define DialogParticleEmitterButtonCancel 1034
#define DialogModelPropertiesEditMinZ   1034
#define DialogPropertiesEditGroundTexture 1034
#define DialogLightButtonOk             1035
#define DialogModelPropertiesEditMaxX   1035
#define DialogPropertiesEditGroundTextureScale 1035
#define DialogLightButtonCancel         1036
#define DialogModelPropertiesEditMaxY   1036
#define DialogHelperButtonOk            1037
#define DialogModelPropertiesEditMaxZ   1037
#define DialogHelperButtonCancel        1038
#define DialogSequenceEditMaxX          1038
#define DialogEventObjectButtonOk       1039
#define DialogSequenceEditMaxY          1039
#define DialogEventObjectButtonCancel   1040
#define DialogSequenceEditMaxZ          1040
#define DialogCollisionShapeButtonOk    1041
#define DialogCollisionShapeButtonCancel 1042
#define DialogCameraButtonOk            1043
#define DialogCameraButtonCancel        1044
#define DialogAttachmentButtonOk        1045
#define DialogCameraButtonPosition      1045
#define DialogParticleEmitter2ButtonOk  1046
#define DialogCameraButtonTarget        1046
#define DialogParticleEmitter2ButtonCancel 1047
#define DialogCameraButtonRotation      1047
#define DialogCameraEditSourceX         1048
#define DialogCameraEditSourceY         1049
#define DialogCameraEditSourceZ         1050
#define DialogCameraEditTargetX         1051
#define DialogCameraEditTargetY         1052
#define DialogCameraEditTargetZ         1053
#define DialogCameraEditFieldOfView     1054
#define DialogCameraEditNearDistance    1055
#define DialogCameraEditFarDistance     1056
#define DialogCameraEditName            1057
#define DialogTextureButtonOk           1058
#define DialogTextureButtonCancel       1059
#define DialogTextureEditName           1060
#define DialogTextureButtonWrapWidth    1061
#define DialogTextureButtonWrapHeight   1062
#define DialogBoneButtonOk              1063
#define DialogBoneButtonCancel          1064
#define DialogGeosetButtonOk            1065
#define DialogGeosetButtonCancel        1066
#define DialogGeosetAnimationButtonOk   1067
#define DialogGeosetButtonVertices      1067
#define DialogGeosetAnimationButtonCancel 1068
#define DialogGeosetButtonFaces         1068
#define DialogGlobalSequenceButtonOk    1069
#define DialogGeosetButtonGroups        1069
#define DialogGlobalSequenceButtonCancel 1070
#define DialogGeosetButtonExtents       1070
#define DialogMaterialButtonOk          1071
#define DialogMaterialButtonCancel      1072
#define DialogNodeEditName              1073
#define DialogNodeButtonOk              1074
#define DialogNodeButtonCancel          1075
#define DialogSequenceEditName          1076
#define DialogNodeButtonTranslation     1076
#define DialogSequenceButtonOk          1077
#define DialogNodeButtonRotation        1077
#define DialogSequenceButtonCancel      1078
#define DialogNodeButtonScaling         1078
#define DialogTextureAnimationButtonOk  1079
#define DialogTextureAnimationButtonCancel 1080
#define DialogModelPropertiesButtonOk   1081
#define DialogModelPropertiesButtonCancel 1082
#define DialogModelPropertiesEditName   1083
#define DialogModelPropertiesEditAnimationFile 1084
#define DialogModelPropertiesEditBlendTime 1085
#define DialogCollisionShapeButtonBox   1086
#define DialogModelPropertiesEditBoundsRadius 1086
#define DialogCollisionShapeButtonSphere 1087
#define DialogSequenceEditMoveSpeed     1087
#define DialogCollisionShapeEditBoundsRadius 1088
#define DialogCollisionShapeEditX1      1089
#define DialogSequenceEditMinX          1089
#define DialogCollisionShapeEditY1      1090
#define DialogSequenceEditMinY          1090
#define DialogCollisionShapeEditZ1      1091
#define DialogSequenceEditMinZ          1091
#define DialogCollisionShapeEditX2      1092
#define DialogSequenceEditRarity        1092
#define DialogCollisionShapeEditY2      1093
#define DialogSequenceEditBoundsRadius  1093
#define DialogCollisionShapeEditZ2      1094
#define DialogSequenceButtonNonLooping  1094
#define DialogSequenceEditFrom          1095
#define DialogMaterialButtonConstantColor 1095
#define DialogSequenceEditTo            1096
#define DialogMaterialButtonSortPrimitivesFarZ 1096
#define DialogMaterialButtonFullResolution 1097
#define DialogMaterialEditPriorityPlane 1098
#define DialogTextureEditReplaceableId  1100
#define DialogNodeEditX                 1101
#define DialogNodeEditY                 1102
#define DialogNodeEditZ                 1103
#define DialogNodeButtonDontInheritTranslation 1104
#define DialogNodeButtonDontInheritRotation 1105
#define DialogCameraButtonAnimatedPosition 1105
#define DialogNodeButtonDontInheritScaling 1106
#define DialogCameraButtonAnimatedTarget 1106
#define DialogGeosetEditBoundsRadius    1106
#define DialogNodeButtonBillboarded     1107
#define DialogCameraButtonAnimatedRotation 1107
#define DialogGeosetEditSelectionGroup  1107
#define DialogNodeButtonBillboardedLockX 1108
#define DialogGeosetButtonUnselectable  1108
#define DialogNodeButtonBillboardedLockY 1109
#define DialogGeosetEditMinX            1109
#define DialogNodeButtonBillboardedLockZ 1110
#define DialogGeosetEditMinY            1110
#define DialogNodeButtonCameraAnchored  1111
#define DialogGeosetEditMinZ            1111
#define DialogGeosetEditMaxX            1112
#define DialogGeosetEditMaxY            1113
#define DialogGeosetEditMaxZ            1114
#define DialogGeosetComboMaterialId     1115
#define DialogGlobalSequenceEditDuration 1116
#define DialogTextureAnimationButtonAnimatedTranslation 1117
#define DialogTextureAnimationButtonAnimatedRotation 1118
#define DialogTextureAnimationButtonAnimatedScaling 1119
#define DialogTextureAnimationButtonTranslation 1120
#define DialogTextureAnimationButtonRotation 1121
#define DialogInterpolatorButtonOk      1121
#define DialogTextureAnimationButtonScaling 1122
#define DialogInterpolatorButtonCancel  1122
#define DialogGeosetAnimationButtonAnimatedColor 1123
#define DialogGeosetAnimationButtonAnimatedAlpha 1124
#define DialogGeosetAnimationButtonAlpha 1125
#define DialogGeosetAnimationButtonColor 1126
#define DialogGeosetAnimationComboGeosetId 1127
#define DialogGeosetAnimationButtonUseColor 1128
#define DialogGeosetAnimationButtonDropShadow 1129
#define DialogGeosetAnimationColor      1130
#define DialogGeosetAnimationButtonPick 1131
#define DialogGeosetAnimationEditAlpha  1134
#define DialogEventObjectComboGlobalSequenceId 1135
#define DialogEventObjectList           1136
#define DialogTrackButtonOk             1137
#define DialogTrackButtonCancel         1138
#define DialogTrackEditTime             1139
#define DialogLightButtonAnimatedColor  1140
#define DialogLightButtonAnimatedAmbientColor 1141
#define DialogLightButtonAnimatedAttenuationStart 1142
#define DialogLightButtonAnimatedAttenuationEnd 1143
#define DialogLightButtonAnimatedIntensity 1144
#define DialogLightButtonAnimatedAmbientIntensity 1145
#define DialogLightButtonAnimatedVisibility 1146
#define DialogLightButtonColor          1147
#define DialogLightButtonAmbientColor   1148
#define DialogLightButtonAttenuationStart 1149
#define DialogLightButtonAttenuationEnd 1150
#define DialogLightButtonIntensity      1151
#define DialogLightButtonAmbientIntensity 1152
#define DialogLightButtonVisibility     1153
#define DialogLightColor                1154
#define DialogLightAmbientColor         1155
#define DialogLightButtonPickColor      1156
#define DialogLightButtonPickAmbientColor 1157
#define DialogLightEditIntensity        1158
#define DialogLightEditAmbientIntensity 1159
#define DialogLightEditAttenuationStart 1160
#define DialogLightEditAttenuationEnd   1161
#define DialogLightEditVisibility       1162
#define DialogLightComboType            1163
#define DialogBoneComboGeosetId         1164
#define DialogBoneComboGeosetAnimationId 1165
#define DialogRibbonEmitterButtonAnimatedColor 1167
#define DialogRibbonEmitterButtonAnimatedAlpha 1168
#define DialogRibbonEmitterButtonAnimatedVisibility 1169
#define DialogRibbonEmitterButtonAnimatedHeightAbove 1170
#define DialogRibbonEmitterButtonAnimatedHeightBelow 1171
#define DialogRibbonEmitterButtonAnimatedTextureSlot 1172
#define DialogRibbonEmitterButtonColor  1173
#define DialogRibbonEmitterButtonAlpha  1174
#define DialogRibbonEmitterButtonVisibility 1175
#define DialogRibbonEmitterButtonHeightAbove 1176
#define DialogRibbonEmitterButtonHeightBelow 1177
#define DialogRibbonEmitterButtonTextureSlot 1178
#define DialogRibbonEmitterColor        1179
#define DialogRibbonEmitterButtonPickColor 1180
#define DialogRibbonEmitterEditAlpha    1181
#define DialogRibbonEmitterEditVisibility 1182
#define DialogRibbonEmitterEditTextureSlot 1183
#define DialogRibbonEmitterEditHeightAbove 1184
#define DialogRibbonEmitterEditHeightBelow 1185
#define DialogRibbonEmitterEditRows     1186
#define DialogRibbonEmitterEditColumns  1187
#define DialogRibbonEmitterEditEmissionRate 1188
#define DialogRibbonEmitterEditLifeSpan 1189
#define DialogRibbonEmitterEditGravity  1190
#define DialogRibbonEmitterComboMaterialId 1191
#define DialogParticleEmitterButtonAnimatedEmissionRate 1192
#define DialogParticleEmitterButtonAnimatedLifeSpan 1193
#define DialogParticleEmitterButtonAnimatedInitialVelocity 1194
#define DialogParticleEmitterButtonAnimatedGravity 1195
#define DialogParticleEmitterButtonAnimatedLongitude 1196
#define DialogParticleEmitterButtonAnimatedLatitude 1197
#define DialogParticleEmitterButtonEmissionRate 1198
#define DialogParticleEmitterButtonLifeSpan 1199
#define DialogParticleEmitterButtonInitialVelocity 1200
#define DialogParticleEmitterButtonGravity 1201
#define DialogParticleEmitterButtonLongitude 1202
#define DialogParticleEmitterButtonLatitude 1203
#define DialogParticleEmitterEditEmissionRate 1204
#define DialogParticleEmitterEditLifeSpan 1205
#define DialogParticleEmitterEditInitialVelocity 1206
#define DialogParticleEmitterEditGravity 1207
#define DialogParticleEmitterEditLongitude 1208
#define DialogParticleEmitterEditLatitude 1209
#define DialogParticleEmitterButtonUsesMdl 1210
#define DialogParticleEmitterEditFileName 1211
#define DialogParticleEmitterButtonUsesTga 1212
#define DialogParticleEmitter2ButtonAnimatedVisibility 1212
#define DialogParticleEmitterButtonAnimatedVisibility 1213
#define DialogParticleEmitter2ButtonAnimatedEmissionRate 1213
#define DialogParticleEmitterButtonVisibility 1214
#define DialogParticleEmitterEditVisibility 1215
#define DialogParticleEmitter2ButtonAnimatedSpeed 1216
#define DialogParticleEmitter2ButtonAnimatedVariation 1217
#define DialogParticleEmitter2ButtonAnimatedWidth 1218
#define DialogParticleEmitter2ButtonAnimatedLength 1219
#define DialogParticleEmitter2ButtonAnimatedGravity 1220
#define DialogParticleEmitter2ButtonAnimatedLatitude 1221
#define DialogParticleEmitter2ButtonVisibility 1222
#define DialogParticleEmitter2ButtonEmissionRate 1223
#define DialogParticleEmitter2ButtonSpeed 1224
#define DialogParticleEmitter2ButtonVariation 1225
#define DialogParticleEmitter2ButtonWidth 1226
#define DialogParticleEmitter2ButtonLength 1227
#define DialogParticleEmitter2ButtonGravity 1228
#define DialogParticleEmitter2ButtonLatitude 1229
#define DialogParticleEmitter2EditVisibility 1230
#define DialogParticleEmitter2EditEmissionRate 1231
#define DialogParticleEmitter2EditSpeed 1232
#define DialogParticleEmitter2EditVariation 1233
#define DialogParticleEmitter2EditWidth 1234
#define DialogParticleEmitter2EditLength 1235
#define DialogParticleEmitter2EditGravity 1236
#define DialogParticleEmitter2EditLatitude 1237
#define DialogParticleEmitter2Color1    1238
#define DialogParticleEmitter2Color2    1239
#define DialogParticleEmitter2Color3    1240
#define DialogParticleEmitter2ButtonPickColor1 1241
#define DialogParticleEmitter2ButtonPickColor2 1242
#define DialogParticleEmitter2ButtonPickColor3 1243
#define DialogParticleEmitter2EditAlpha1 1244
#define DialogParticleEmitter2EditAlpha2 1245
#define DialogParticleEmitter2EditAlpha3 1246
#define DialogParticleEmitter2EditScaling1 1247
#define DialogParticleEmitter2EditScaling2 1248
#define DialogParticleEmitter2EditScaling3 1249
#define DialogParticleEmitter2EditLifeSpan1 1250
#define DialogParticleEmitter2EditLifeSpan2 1251
#define DialogParticleEmitter2EditLifeSpan3 1252
#define DialogParticleEmitter2EditDecay1 1253
#define DialogParticleEmitter2EditDecay2 1254
#define DialogParticleEmitter2EditDecay3 1255
#define DialogParticleEmitter2EditLifeSpanTail1 1256
#define DialogParticleEmitter2EditLifeSpanTail2 1257
#define DialogParticleEmitter2EditLifeSpanTail3 1258
#define DialogParticleEmitter2EditDecayTail1 1259
#define DialogParticleEmitter2EditDecayTail2 1260
#define DialogParticleEmitter2EditDecayTail3 1261
#define DialogParticleEmitter2EditRows  1262
#define DialogParticleEmitter2EditColumns 1263
#define DialogParticleEmitter2EditPriorityPlane 1264
#define DialogParticleEmitter2EditReplaceableId 1265
#define DialogParticleEmitter2EditTime  1266
#define DialogParticleEmitter2EditLifeSpan 1267
#define DialogParticleEmitter2EditTailLength 1268
#define DialogParticleEmitter2ComboTextureId 1269
#define DialogParticleEmitter2ButtonUnshaded 1270
#define DialogEventObjectCombo1         1270
#define DialogParticleEmitter2ButtonUnfogged 1271
#define DialogEventObjectCombo2         1271
#define DialogParticleEmitter2ButtonXYQuad 1272
#define DialogEventObjectEditData       1272
#define DialogParticleEmitter2ButtonSquirt 1273
#define DialogEventObjectEditIdentifier 1273
#define DialogMaterialLayerButtonOk     1273
#define DialogParticleEmitter2ButtonHead 1274
#define DialogMaterialLayerButtonCancel 1274
#define DialogParticleEmitter2ButtonTail 1275
#define DialogMaterialList              1275
#define DialogParticleEmitter2ButtonAlphaKey 1276
#define DialogMaterialLayerButtonAnimatedTextureId 1276
#define DialogParticleEmitter2ButtonModelSpace 1277
#define DialogMaterialLayerButtonTextureId 1277
#define DialogParticleEmitter2ButtonLineEmitter 1278
#define DialogMaterialLayerComboTextureId 1278
#define DialogParticleEmitter2ButtonSortPrimitivesFarZ 1279
#define DialogMaterialLayerEditAlpha    1279
#define DialogMaterialLayerButtonAnimatedAlpha 1280
#define DialogParticleEmitter2ComboFilterMode 1280
#define DialogMaterialLayerButtonAlpha  1281
#define DialogMaterialLayerComboTextureAnimationId 1282
#define DialogMaterialLayerButtonUnshaded 1283
#define DialogMaterialLayerButtonUnfogged 1284
#define DialogMaterialLayerComboFilterMode 1285
#define DialogMaterialLayerButtonSphereEnvironmentMap 1286
#define DialogMaterialLayerButtonNoDepthTest 1287
#define DialogMaterialLayerButtonNoDepthSet 1288
#define DialogMaterialLayerButtonTwoSided 1289
#define DialogInterpolatorEdit          1296
#define DialogInterpolatorComboGlobalSequenceId 1297
#define DialogInterpolatorComboInterpolationType 1298
#define DialogModelInfoButtonOk         1298
#define DialogModelInfoTextGeoset       1299
#define DialogModelInfoTextGeosetAnimation 1300
#define DialogImportGeosetButtonOk      1300
#define DialogModelInfoTextTexture      1301
#define DialogImportGeosetButtonCancel  1301
#define DialogModelInfoTextTextureAnimation 1302
#define DialogImportGeosetCombo         1302
#define DialogModelInfoTextMaterial     1303
#define DialogLoadingScreenButtonOk     1303
#define DialogModelInfoTextSequence     1304
#define DialogLoadingScreenButtonCancel 1304
#define DialogModelInfoTextGlobalSequence 1305
#define DialogLoadingScreenEditTextureFileName 1305
#define DialogModelInfoTextCamera       1306
#define DialogLoadingScreenButtonPick   1306
#define DialogTranslateButtonOk         1306
#define DialogModelInfoTextAttachment   1307
#define DialogLoadingScreenButtonGenerate 1307
#define DialogTranslateButtonCancel     1307
#define DialogModelInfoTextBone         1308
#define DialogRotateButtonOk            1308
#define DialogModelInfoTextCollisionShape 1309
#define DialogRotateButtonCancel        1309
#define DialogModelInfoTextEventObject  1310
#define DialogScaleButtonOk             1310
#define DialogModelInfoTextHelper       1311
#define DialogScaleButtonCancel         1311
#define DialogModelInfoTextLight        1312
#define DialogTranslateEditX            1312
#define DialogModelInfoTextParticleEmitter 1313
#define DialogTranslateEditY            1313
#define DialogModelInfoTextParticleEmitter2 1314
#define DialogTranslateEditZ            1314
#define DialogModelInfoTextRibbonEmitter 1315
#define DialogScaleEditPivotX           1315
#define DialogModelInfoTextVertex       1316
#define DialogScaleEditPivotY           1316
#define DialogModelInfoTextFace         1317
#define DialogScaleEditPivotZ           1317
#define DialogModelInfoTextGroup        1318
#define DialogScaleEditX                1318
#define DialogModelInfoTextAnimationLength 1319
#define DialogScaleEditY                1319
#define DialogModelInfoTextTrack        1320
#define DialogScaleEditZ                1320
#define DialogRotateEditPivotX          1321
#define DialogRotateEditPivotY          1322
#define DialogRotateEditPivotZ          1323
#define DialogRotateButtonX             1324
#define DialogRotateEditA               1325
#define DialogFacesButtonOk             1325
#define DialogRotateButtonY             1326
#define DialogFacesButtonCancel         1326
#define DialogRotateButtonZ             1327
#define DialogVerticesButtonOk          1327
#define DialogRotateButtonAxis          1328
#define DialogVerticesButtonCancel      1328
#define DialogRotateButtonQuaternion    1329
#define DialogGroupsButtonOk            1329
#define DialogRotateEditB               1330
#define DialogGroupsButtonCancel        1330
#define DialogRotateEditC               1331
#define DialogExtentsButtonOk           1331
#define DialogRotateEditD               1332
#define DialogExtentsButtonCancel       1332
#define DialogRotateEditAngle           1333
#define DialogExtentsList               1333
#define DialogRotateEditAxisX           1334
#define DialogFacesList                 1334
#define DialogRotateEditAxisY           1335
#define DialogGroupsList                1335
#define DialogRotateEditAxisZ           1336
#define DialogVerticesList              1336
#define DialogVertexButtonOk            1337
#define DialogRotateButtonUsePivotPoint 1337
#define DialogVertexButtonCancel        1338
#define DialogRotateButtonUseCentreOfMass 1338
#define DialogExtentButtonOk            1339
#define DialogRotateButtonRadians       1339
#define DialogExtentButtonCancel        1340
#define DialogRotateButtonUseCentreOfMass2 1340
#define DialogRotateButtonDegrees       1340
#define DialogFaceButtonOk              1341
#define DialogFaceButtonCancel          1342
#define DialogGroupButtonOk             1343
#define DialogGroupButtonCancel         1344
#define DialogFaceComboIndex1           1346
#define DialogFaceComboIndex2           1347
#define DialogVertexEditX               1347
#define DialogFaceComboIndex3           1348
#define DialogVertexComboGroup          1348
#define DialogVertexEditY               1349
#define DialogExtentEditMinX            1349
#define DialogVertexEditZ               1350
#define DialogExtentEditMinY            1350
#define DialogVertexEditNormalX         1351
#define DialogExtentEditMinZ            1351
#define DialogVertexEditNormalY         1352
#define DialogExtentEditMaxX            1352
#define DialogVertexEditNormalZ         1353
#define DialogExtentEditMaxY            1353
#define DialogExtentEditMaxZ            1354
#define DialogVertexEditTextureX        1354
#define DialogExtentEditBoundsRadius    1355
#define DialogVertexEditTextureY        1355
#define DialogGroupEdit                 1356
#define DialogAttachmentEditPath        1357
#define DialogScaleButtonUsePivotPoint  1359
#define DialogScaleButtonUseCentreOfMass 1360
#define MainWindowsModelEditor          40003
#define MainWindowsMpqBrowser           40004
#define MainHelpAbout                   40006
#define MainFileNew                     40013
#define MainFileOpen                    40014
#define MainFileSave                    40015
#define MainFileSaveAs                  40016
#define MainFileClose                   40017
#define MainFileExit                    40018
#define MainTeamColorRed                40019
#define MainTeamColorBlue               40020
#define MainTeamColorTeal               40022
#define MainTeamColorPurple             40023
#define MainTeamColorYellow             40024
#define MainTeamColorOrange             40025
#define MainTeamColorGreen              40026
#define MainTeamColorPink               40027
#define MainTeamColorGray               40028
#define MainTeamColorLightBlue          40029
#define MainTeamColorDarkGreen          40030
#define MainTeamColorBrown              40031
#define MainTeamColorBlack              40032
#define ModelViewResize                 40035
#define MainViewResize                  40037
#define MpqFileOpen                     40041
#define MpqFileClose                    40042
#define MpqFiltersAll                   40045
#define MpqFiltersNone                  40046
#define MainEditRegisterExtentions      40048
#define MpqFiltersOther                 40051
#define MpqViewAutoSort                 40053
#define MpqPopupOpen                    40056
#define MpqPopupExport                  40057
#define MpqFileWar3Mpq                  40059
#define MpqFileWar3xMpq                 40060
#define MpqFileWar3xLocalMpq            40061
#define MpqFileWar3PatchMpq             40062
#define MainEditProperties              40064
#define MainViewResetCamera             40065
#define MainWindowsAnimationController  40067
#define MainWindowsTextureManager       40069
#define TextureFileImport               40070
#define TextureFileExport               40071
#define TextureFileRemove               40072
#define TextureFileView                 40077
#define TextureFileView2                40079
#define TextureFileImport2              40080
#define TextureFileExport2              40081
#define TextureFileRemove2              40082
#define MpqPopupUseAsTexture            40087
#define MpqPopupOpen2                   40088
#define MpqPopupExport2                 40089
#define MpqPopupUseAsTexture2           40091
#define MainExtrasColoredText           40092
#define MainWindowsHelperManager        40095
#define MainWindowsAttachmentManager    40096
#define MainWindowsRibbonEmitterManager 40097
#define MainWindowsParticleEmitterManager 40098
#define MainWindowsCollisionShapeManager 40099
#define MainWindowsCameraManager        40100
#define MainWindowsEventObjectManager   40101
#define ManagerFileRemove               40110
#define ManagerFileEdit                 40111
#define ManagerFileCreate2              40112
#define ManagerFileCreate               40113
#define ManagerFileRemove2              40114
#define ManagerFileEdit2                40115
#define TextureFileEdit                 40119
#define TextureFileEdit2                40121
#define ID_VIEW_DISPLAYCAMERAS          40122
#define ID_VIEW_DISPLAYHELPERS          40123
#define CameraFileCreate                40135
#define CameraFileRemove                40136
#define CameraFileEdit                  40137
#define CameraFileView                  40138
#define CameraFileCreate2               40139
#define CameraFileRemove2               40140
#define CameraFileEdit2                 40141
#define CameraFileView2                 40142
#define MainWindowsTextureAnimationManager 40143
#define MainWindowsSequenceManager      40144
#define MainWindowsMaterialManager      40145
#define MainWindowsGlobalSequenceManager 40146
#define MainWindowsGeosetAnimationManager 40147
#define MainWindowsGeosetManager        40148
#define MainWindowsNodeManager          40150
#define MainEditModelProperties         40153
#define NodeFileRemove                  40165
#define NodeFileEditNode                40166
#define NodeFileEdit                    40167
#define NodeFileCreateBone              40168
#define NodeFileCreateHelper            40169
#define NodeFileCreateLight             40170
#define NodeFileCreateParticleEmitter   40171
#define NodeFileCreateParticleEmitter2  40172
#define NodeFileCreateRibbonEmitter     40173
#define NodeFileCreateCollisionShape    40174
#define NodeFileCreateAttachment        40175
#define NodeFileCreateAttachment2       40176
#define NodeFileCreateBone2             40177
#define NodeFileCreateCollisionShape2   40178
#define NodeFileCreateHelper2           40179
#define NodeFileCreateLight2            40180
#define NodeFileCreateRibbonEmitter2    40182
#define NodeFileEdit2                   40183
#define NodeFileEditNode2               40184
#define NodeFileRemove2                 40185
#define NodeFileCreateEventObject       40187
#define NodeFileCreateEventObject2      40189
#define NodeFileCreateParticleEmitter2_2 40190
#define NodeFileCreateParticleEmitter2_1 40191
#define TextureFileCreateEmpty          40193
#define TextureFileCreateEmpty2         40194
#define TrackFileCreateNew              40196
#define TrackFileRemove                 40198
#define TrackFileCreateNew2             40199
#define TrackFileRemove2                40200
#define NodeFileMoveUp                  40205
#define NodeFileMoveDown                40206
#define NodeFileMoveLeft                40207
#define NodeFileMoveRight               40208
#define NodeFileMoveUp2                 40213
#define NodeFileMoveDown2               40214
#define NodeFileMoveLeft2               40215
#define NodeFileMoveRight2              40216
#define LayerFileCreateNew              40222
#define LayerFileEdit                   40223
#define LayerFileRemove                 40224
#define LayerFileMoveUp                 40225
#define LayerFileMoveDown               40226
#define LayerFileCreateNew2             40227
#define LayerFileEdit2                  40228
#define LayerFileRemove2                40229
#define LayerFileMoveUp2                40230
#define LayerFileMoveDown2              40231
#define NodeFileDuplicate               40233
#define NodeFileDuplicate2              40235
#define MainEditModelInfo               40237
#define GeosetFileCreate                40244
#define GeosetFileRemove                40245
#define GeosetFileImport                40246
#define GeosetFileExport                40247
#define GeosetFileEdit                  40248
#define GeosetFileCreate2               40249
#define GeosetFileRemove2               40250
#define GeosetFileImport2               40251
#define GeosetFileExport2               40252
#define GeosetFileEdit2                 40253
#define MpqPopupCopyPath                40255
#define MpqPopupCopyPath2               40257
#define MainExtrasLoadingScreen         40259
#define MainHistoryClear                40261
#define MainEditCalculateExtents        40263
#define ModelTransformationsTranslate   40265
#define ModelTransformationsRotate      40267
#define ModelTransformationsScale       40269
#define ModelSelectionAll               40272
#define ModelSelectionNone              40273
#define MainFileImport                  40275
#define CameraFileCreateView            40277
#define CameraFileCreateView2           40279
#define MainHelpHelp                    40281
#define VertexFileCreate                40282
#define VertexFileRemove                40283
#define VertexFileEdit                  40284
#define ExtentFileCreate                40285
#define ExtentFileRemove                40286
#define ExtentFileEdit                  40287
#define FaceFileCreate                  40288
#define FaceFileRemove                  40289
#define FaceFileEdit                    40290
#define GroupFileCreate                 40291
#define GroupFileRemove                 40292
#define GroupFileEdit                   40293
#define ExtentFileCreate2               40294
#define ExtentFileRemove2               40295
#define ExtentFileEdit2                 40296
#define FaceFileCreate2                 40297
#define FaceFileRemove2                 40298
#define FaceFileEdit2                   40299
#define GroupFileCreate2                40300
#define GroupFileRemove2                40301
#define GroupFileEdit2                  40302
#define VertexFileCreate2               40303
#define VertexFileRemove2               40304
#define VertexFileEdit2                 40305
#define ModelViewXYFront                40307
#define ModelViewXYBack                 40309
#define ModelViewXZFront                40311
#define ModelViewXZBack                 40313
#define ModelViewYZFront                40315
#define ModelViewYZBack                 40317
#define ModelViewNone                   40319
#define ModelViewResetCamera            40322
#define ModelViewResetPivotPoint        40324

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         40333
#define _APS_NEXT_CONTROL_VALUE         1361
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
